export const carBrands: { id: number; label: string; model: string[] }[] = [
  {
    id: 0,
    label: "Honda",
    model: ["City", "Amaze", "WR-V", "HR-V", "Brio"],
  },
  {
    id: 1,
    label: "Maruti Suzuki",
    model: [
      "Vitara Brezza",
      "Swift",
      "Ertiga",
      "Baleno",
      "Alto 800",
      "Dzire",
      "Wagon R",
      "Celerio",
      "S-Cross",
      "XL6",
      "S-Presso",
      "Ciaz",
      "Ignis",
      "Eeco",
    ],
  },
  {
    id: 2,
    label: "Hyundei",
    model: [
      "Grand i10 Nios",
      "i20",
      "Creta",
      "Venue",
      "Verna",
      "Alcazar",
      "Aura",
      "Santro",
      "Tucson",
      "Elantra",
      "Kona Electric",
      "Xcent Prime",
    ],
  },
  {
    id: 3,
    label: "Tata",
    model: [
      "Punch",
      "Harrier",
      "Nexon",
      "Tiago",
      "Altroz",
      "Safari",
      "Tigor",
      "Tiago NRG",
      "Tigor EV",
      "Nexon EV",
    ],
  },
  {
    id: 4,
    label: "Toyota",
    model: [
      "Fortuner",
      "Innova Crysta",
      "Camry",
      "Vellfire",
      "Glanza",
      "Urban Cruiser",
    ],
  },
  {
    id: 5,
    label: "Kia",
    model: ["Seltos", "Sonet", "Carnival"],
  },
  {
    id: 6,
    label: "Skoda",
    model: ["Kushaq", "Rapid", "Octavia", "Superb"],
  },
  {
    id: 7,
    label: "MG",
    model: ["Hector", "Astor", "Gloster", "ZS EV", "Hector Plus"],
  },
  {
    id: 8,
    label: "Mercedes",
    model: ["GLA", "GLC", "S-Class", "E-Class", "GLS", "V-Class"],
  },
  {
    id: 9,
    label: "Volkswagen",
    model: ["Polo", "Taigun", "Tiguan", "Vento"],
  },
  {
    id: 10,
    label: "Renault",
    model: ["KWID", "Triber", "Kiger", "Duster"],
  },
  {
    id: 11,
    label: "Mahindra",
    model: [
      "Thar",
      "XUV500",
      "XUV700",
      "Scorpio",
      "Bolero",
      "XUV300",
      "Marazzo",
      "Alturas G4",
      "KUV100 NXT",
      "E Verito",
      "Bolero Neo",
    ],
  },
  {
    id: 12,
    label: "Jeep",
    model: ["Compass", "Wrangler"],
  },
  {
    id: 13,
    label: "Nissan",
    model: ["Magnite", "Kicks", "GT-R"],
  },
  {
    id: 14,
    label: "Datsun",
    model: ["GO", "redi-GO", "GO Plus"],
  },
];

export const carType: string[] = ["Sedan", "Hachback", "Micro SUV"];
export const fuelType: string[] = [
  "Petrol ",
  "Petrol + CNG",
  "Petrol + LPG",
  "Diesel",
  "Electric vehicle",
];
